<?php
class Curriculum
{
    static public function get() {
        return [
                "double-bass" =>
                    "Luca Di Chiara, classe '88, inizia il suo percorso musicale a 14 anni quando decide di iscriversi a contrabbasso presso l'Istituto Musicale Angelo Masini di Forlì, sotto la guida del M° Maurizio Tassani. Qui rimane per 6 anni, prima di decidere che la musica sarebbe diventata il suo lavoro e di intraprendere il Triennio di Contrabbasso classico presso il conservatorio G. Rossini di Pesaro, sotto la guida del M° Caffiero Gobbi. Dopo aver frequentato masterclass dei M° Bocini, M° Salentini, M° Donati, M° Serra e M° Pignoni, si laurea nel 2012 con 104/110, scrivendo una tesi dal titolo \"L'Evoluzione della musica dalla Suite barocca alla Suite progressive\", incentrata sul Progressive inglese degli anni '70 con approfondimento sui Genesis di Peter Gabriel; prosegue e conclude gli studi accademici nello stesso conservatorio laureandosi al Biennio di II livello nel 2015 con 110/110 e portando sul palco anche brani arrangiati personalmente. In questi anni approfondisce anche le sue conoscenze del basso elettrico jazz con una masterclass del M° Rolli e del basso rock col M° Claudio \"Gallo\" Golinelli, storico e attuale bassista di Vasco Rossi.
Dopo diverse esperienze con varie orchestre, tra cui la Filarmonica Marchigiana, diventa Primo Contrabbasso dell'orchestra Corelli di Ravenna, nella quale milita attualmente; in ambito classico è anche parte dell'Ensemble Orpheus di Forlì.
La sua passione per il polistrumentismo lo porta ad approfondire anche altri strumenti, divenendo chitarrista del duo Iza&Sara, per le quali ha arrangiato gran parte dei brani di \"Rebis\", album di esordio, e di Iza Trio; fa parte anche degli Alterego Blues Band come bassista e della Old Station Big Band come trombonista. Si è esibito anche con un omonimo progetto solista, in cui tramite l'uso della loop station suona contrabbasso, chitarre, tastiere, trombone, percussioni ricreando un'intera band da solo, e a cui ha aggiunto la batteria in un nuovo progetto interamente dedicato ai Chemical Brothers.
Insegna contrabbasso, basso elettrico e chitarra presso l'Accademia InArte di Forlì e la scuola di musica G. Rossini di Terra del Sole, dove è anche insegnante di musica d'insieme; tiene inoltre un corso di chitarra collettiva per l'associazione Ri Crea Azione di Villafranca (FC).
Negli EST vuole portare questa sua esperienza globale svincolandosi dal ruolo del classico contrabbassista accompagnatore, fondendo la tecnica jazzistica a quella classica, percuotendo lo strumento come se fosse una batteria, contaminando il suono con effetti elettronici e aggiungendo stompbox e campanaccio.",
                "cello" =>
                    "Antonio Cortesi si è laureato con il massimo dei voti e la lode in violoncello e musica da camera presso il conservatorio B. Maderna di Cesena ricevendo la borsa di studio Rotary Biasini come migliore laureato nel 2015. Ha partecipato come effettivo a masterclasses con Enrico Dindo, Hans Jorgen Jensen, Raphael Wallfisch, Giovanni Gnocchi, Xavier Ganepain, Amit Peled, Natalia Gutman, Luigi Piovano, Francesco Dillon (corso di perfezionamento presso l'accademia di belle arti di Roma), Hanna Roberts (partecipando all'edizione 2017 di London Masterclasses) e Jakob Spahn (Cello akademie Rutesheim 2017). Ha partecipato al progetto Erasmus studiando presso il Conservatorio Superior de musica Manuel Castillo di Siviglia frequentando tra le altre la classe del maestro Andre Cea. Durante il suo percorso accademico ha avuto la possibilità di eseguire il concerto di Haydn n.1 in Do maggiore come solista con l'orchestra del conservatorio Maderna di Cesena. Attualmente frequenta il corso di perfezionamento in Violoncello nella classe di Orfeo Mandozzi presso l’accademia pianistica di Imola e con Marianne Chen presso l’accademia di Pinerolo. Ha suonato con Orchestra giovanile Cherubini, EY Young talents orchestra, World Youth Orchestra, Youth European Musicians Orchestra, Orchestra Pro Musica, Orchestra nazionale dei conservatori italiani, Collegium Musicum di Bologna (avendo ottenuto una borsa di studio come prima parte) e La Corelli di Ravenna. In quest'ultima (La Corelli di Ravenna) è socio della cooperativa e ricopre il ruolo di primo violoncello. E' inoltre attivo con diversi ensemble cameristici con cui si è esibito in festival e rassegne in Italia e all'estero (tra gli altri Aurora chamber music festival, Suona Francese, Musica tra le antiche mura, Giovani in musica di Ravenna, Incontri Mittleeuropei,  Apeldoorn festival  and masterclass, Gubbio summer festival, Lugo Music Festival, Forum de Violonchelo de Espana, Stagione dei Concerti al circolo degli ufficiali di Bologna, San Giacomo festival e Imola summer festival). Suona in duo con il pianista giapponese Ryo Terukina, con il quale ha guadagnato il II premio al concorso di musica da camera \"Premio Crescendo\" di Firenze. Si è esibito come camerista e in orchestra in Russia, Ungheria, Polonia, Francia, Inghilterra, Spagna, Svezia, Iran, Slovenia, Germania, Olanda, Danimarca, Austria, Ucraina, Cina e Repubblica Ceca. Suona un Violoncello Custode Marcucci del 1925. E' inoltre attivo in progetti di musica originale con il trio EST e ha recentemente collaborato con lo scrittore Giuliano Scabia nello spettacolo \"L'azione perfetta\".",
                "violin" =>
                    "Nel 2012 consegue il Diploma di Violino presso l’Istituto Superiore di Studi Musicali “G.Verdi” di Ravenna sotto la guida del M° L.Falasca e del M° L.Bertoni per la Musica da Camera. Ha avuto la possibilità di esibirsi per prestigiose rassegne concertistiche, collaborando con importanti orchestre tra le quali spiccano l’“Orchestra dell’Associazione Arcangelo Corelli di Ravenna”,”Orchestra Da Camera Città di Ravenna”,”Orchestra Città di Ravenna”, “ESO” di Massa - Carrara e la “Youth Musicians European Orchestra” con la quale prende parte a concerti organizzati nella Basilica della Natività di Betlemme. Al percorso classico affianca quello della musica jazz e leggera conseguendo nel 2015 con il massimo dei voti e la lode il diploma accademico di II° livello in Musica Jazz a indirizzo interpretativo e compositivo presso il conservatorio “F.Venezze” di Rovigo, affinando le tecniche di composizione e arrangiamento musicale e in particolare il linguaggio jazz sotto la guida del trombettista Marco Tamburini. Nel 2014 vince le selezioni per entrare a far parte della nascente “Orchestra Nazionale Jazz Giovani Talenti” diretta dal M° Paolo Damiani del Dipartimento Jazz del conservatorio S.Cecilia di Roma, con la quale prende parte a importanti rassegne sia nazionali che europee come Umbria Jazz, Iseo Jazz Festival, Torino Jazz Festival, Nantes Jazz Festival. Dal 2018 è direttore di produzione della cooperativa musicale La Corelli di Ravenna. Affidandosi non solo al violino “classico” ma anche alle sonorità molteplici del violino elettrico, prende parte a numerose rassegne e concorsi nazionali (sia accompagnando cantautori, sia suonando in ensembles con repertorio jazz/pop/ rock/folk/country cantautorale)."
        ];
    }
}
?>
